name: Rollback Node

on:
  workflow_dispatch:
    inputs:
      node:
        description: "Node to Rollback (e.g. pve-media)"
        required: true
      commit:
        description: "Commit SHA to Rollback to"
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}
      
      - name: Deploy rolled-back version
        env: 
          SSH_KEY: ${{ secrets.DEPLOY_SHH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          scp -i ~/.ssh/deploy_key \
            nodes/${{ inputs.node }}/docker-compsose.yml \
            deploy@10.0.1.10:/opt/stacks/${{ inputs.node }}/

          ssh -i ~/.ssh/deploy_key deploy@10.0.1.10 \
          "cd /opt/stacks/${{ inputs.node }} && docker-compose up -d"

          echo "Rolled Back ${{ inputs.node }} to ${{ inputs.commit }}"